/*  
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 Longoron.glb
*/

import React, { useLayoutEffect, useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import gsap from 'gsap';

export const FLOOR_HEIGHT = 2.3;
export const NB_FLOORS = 3;

export function Model(props) {
  const { nodes, materials } = useGLTF('../../public/models/Longoron.glb')
  const ref=useRef();
  const tl=useRef();

  const scroll = useScroll();

  useFrame(() => {
tl.current.seek(scroll.offset * tl.current.duration());

  });


  useLayoutEffect (() => {
    tl.current = gsap.timeline();

    // VERTICAL ANIMATION
    tl.current.to(
      ref.current.position,
      {
        duration: 2,
        y: -FLOOR_HEIGHT * (NB_FLOORS - 1),
      },
      0
    );
  }, []);


  return (
    <group {...props} dispose={null} ref={ref}>
      <mesh geometry={nodes.Cube001_1.geometry} material={materials['Longoron_sin_aletas.001']} />
      <mesh geometry={nodes.Cube001_2.geometry} material={materials['Longoron_cuerpo.001']} />
    </group>
  )
}

useGLTF.preload('../../public/models/Longoron.glb')
  
